apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fiap-todo-prod

resources:
- ../../base

patchesStrategicMerge:
- deployment-patch.yaml

commonLabels:
  environment: production

images:
- name: fiap-todo-api
  newName: 860721974296.dkr.ecr.us-east-1.amazonaws.com/fiap-todo-api
  newTag: c6bb46db040f649d73f4df0dd5f33000055b37f7
